# Generated by Django 4.1.4 on 2022-12-12 21:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(110), django.core.validators.MinValueValidator(1)], verbose_name='Idade')),
                ('cep', models.CharField(max_length=11, null=True, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=10, null=True, verbose_name='Numero')),
                ('complement', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('district', models.CharField(max_length=40, verbose_name='Bairro')),
                ('state', models.CharField(max_length=26, verbose_name='Estado')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional', models.CharField(max_length=100, verbose_name='Profissional')),
                ('exam_date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(verbose_name='Peso')),
                ('height', models.FloatField(verbose_name='Altura')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
            ],
        ),
    ]
